# Dockerfile.worker

# Step 1: Base image
FROM python:3.9-slim

# Set the environment variable for the timezone
ENV TZ=UTC

# Install system packages and configure the timezone
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    libssl-dev \
    swig \
    poppler-utils \
    tesseract-ocr \
    tzdata && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Step 3: Create and use working directory
WORKDIR /app

# Step 4: Copy requirements file into /app
COPY requirements.txt /app/

# Step 5: Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install additional packages
RUN pip install --upgrade openai
RUN pip install --upgrade pinecone-client
RUN pip install --upgrade chardet
RUN pip install --upgrade celery
RUN pip install --upgrade PyPDF2

# Step 6: Copy the rest of the code
COPY . /app/

# Step 7: Expose a port if needed 
# EXPOSE 5000

# Step 8: Command to start the Celery worker
CMD ["celery", "-A", "celery_app", "worker", "--loglevel=INFO"]
